### ISSUE TITLE
Firstrunwizard 1.2.0 Testplan

### ISSUE THREAD

**Issue by dpakach** [owncloud/firstrunwizard#102]
## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
Enable firstrunwizard app via CLI using ```occ app:enable firstrunwizard``` | The apps gets enabled | :heavy_check_mark:  |
Disable firstrunwizard app via CLI using ```occ app:disable firstrunwizard``` | The apps gets disabled | :heavy_check_mark:  |
The administrator resets firstrunwizard for all users with ```occ firstrunwizard:reset-all``` and a user logs in | The user sees first run wizard dialog | :heavy_check_mark: |
The administrator resets firstrunwizard for all users with ```occ firstrunwizard:reset-all``` and a user logs, logs out and relogs in | The user sees first run wizard dialog in first login but not in second login | :heavy_check_mark: |
The administrator resets firstrunwizard for all users with ```occ firstrunwizard:reset-all``` and a user logs in, logs out and another user logs in | Both users see first run wizard dialog | :heavy_check_mark: |
**WEBUI tests** |  |   |
When the firstrunwizard is enabled create new user and login | The user sees first run wizard dialog | :heavy_check_mark: |
When the firstrunwizard is disabled create new user and login | The user does not see first run wizard dialog | :heavy_check_mark: |
When the firstrunwizard is enabled, new user logs in for first time, logs out and relogs in | The user does not see first run wizard dialog | :heavy_check_mark:|
When the firstrunwizard is disabled, new user logs in for first time, logs out and relogs in | The user does not see first run wizard dialog | :heavy_check_mark:|
**webUI with several browsers**|  |   |
Check that first run wizard dialog is shown properly using Safari as browser|  | :construction:  |
Check that first run wizard dialog is shown properly using Chrome as browser|  | :heavy_check_mark:  |
Check that first run wizard dialog is shown properly using Firefox as browser|  | :heavy_check_mark:  |
Check that first run wizard dialog is shown properly using IE 11 as browser|  | :heavy_check_mark:  |
Check that first run wizard dialog is shown properly using Edge as browser|  | :heavy_check_mark:  |

**Comment by PVince81** [comment]
we can skip Safari, it is very likely that this already worked
