### ISSUE TITLE
iOS link in first run wizard points to older app

### ISSUE THREAD

**Issue by haukman** [owncloud/firstrunwizard#119]
Just noticed, that the link in the first run wizards points you to the old iOS App:

<img width="1024" alt="grafik" src="https://user-images.githubusercontent.com/25486818/67943558-84be0a00-fbda-11e9-8c2f-0e1fff9a20a5.png">

...using the following link: https://apps.apple.com/us/app/owncloud/id543672169

Correct would be a link to the new iOS App: https://apps.apple.com/app/id1359583808

**Comment by hurradieweltgehtunter** [comment]
Will take care of it in a general rewrite: https://github.com/owncloud/firstrunwizard/issues/147
