### ISSUE TITLE
Branded download links of clients aren't correctly shown in the wizard (stable7)

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/firstrunwizard#18]
The download links for mobile clients aren't being branded in the wizard in stable7. I haven't checked for OC8.

Is it possible to backport that piece of code?

**Comment by rperezb** [comment]
@MTRichards not sure how important this is

**Comment by DeepDiver1975** [comment]
Urls are themable in OC8 - https://github.com/owncloud/core/blob/master/lib/private/defaults.php#L38

**Comment by DeepDiver1975** [comment]
same for stable7 - https://github.com/owncloud/core/blob/stable7/lib/private/defaults.php#L38

**Comment by DeepDiver1975** [comment]
Do I miss anything? THX

**Comment by jvillafanez** [comment]
That's true, but the wizard doesn't pick the urls in stable7 code - https://github.com/owncloud/firstrunwizard/blob/stable7/wizard.php#L33
