### ISSUE TITLE
Wrong doc link in welcome screen

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/firstrunwizard#21]
If I knew where to fix this I would do it-- on the Welcome screen on 8.0.2 Enterprise, the documentation link is incorrect. Enterprise Subscription URLs do not use the EE convention anymore, for example https://doc.owncloud.com/server/8.0EE/. Now it's the same as the community docs, https://doc.owncloud.com/server/8.0/  So the doc link on the Welcome screen should be http://doc.owncloud.com/server/8.0/go.php?to=user-manual

![incorrect-doc-link](https://cloud.githubusercontent.com/assets/8388387/6722086/da57ef84-cd91-11e4-88d7-0786aef3d84a.png)

**Comment by DeepDiver1975** [comment]
that link is generated based on information in the theme - https://github.com/owncloud/enterprise/blob/stable8/theme/defaults.php#L92

**Comment by carlaschroder** [comment]
Cool, thanks @DeepDiver1975 !

fixed https://github.com/owncloud/enterprise/pull/583

**Comment by carlaschroder** [comment]
BTW this is for 8.x only-- older versions are still the same, e.g.  doc.owncloud.com/server/7.0EE/
