### ISSUE TITLE
[Feature Request] users should be asked to enter important information after (first) login

### ISSUE THREAD

**Issue by ryno83** [owncloud/firstrunwizard#25]
_From @j-ed on March 16, 2013 14:59_

When a user logs in for the first time he should automatically be asked to enter 
- his email address, which is required to receive a password reset link.
- his display name, which is used for display purposes.

Due to the fact that other apps might require initial data to be entered too, like the Roundcube app which requires email account credentials, it would be good to provide a generic plugin interface to request that kind of data.

_Copied from original issue: owncloud/core#2379_

**Comment by ryno83** [comment]
_From @jancborchardt on March 17, 2013 12:43_

@j-ed great point! We can add that to the first run wizard. Do you want to contribute and try to take a stab at it? The first run wizard lives at https://github.com/owncloud/apps/tree/master/firstrunwizard, you can let me know if you need help. :)
We don’t really want to offer a pluggable method for that though because then apps can just clutter that up. Email address and display name already covers most.

**Comment by ryno83** [comment]
@jancborchardt I would like to try this one as my first junior job. Are you agree ? Do you have advices for me (thing to do OR not to do) ?

**Comment by ryno83** [comment]
_From @jancborchardt on May 11, 2015 20:30_

@ryno83 cool! First I would say check out how different other web services do that, like Twitter, Facebook, Dropbox, Google, etc. Then make a mockup ([Pencil](http://pencil.evolus.vn/) is good for that) and accompanying description of how you would design it. Does that work for you?

You are also very welcome in our IRC channels #owncloud-design and #owncloud-dev in case of any questions. :) – cc @owncloud/designers

**Comment by ryno83** [comment]
@jancborchardt I think it should be keep simple than look what i did until now. 
![page_1](https://cloud.githubusercontent.com/assets/11739049/7655125/9c1ad17e-faef-11e4-86a6-223ec7341926.png)
![page_2](https://cloud.githubusercontent.com/assets/11739049/7655134/a6986864-faef-11e4-901e-4fa3633ff76e.png)
![page_3](https://cloud.githubusercontent.com/assets/11739049/7655140/a9ca2270-faef-11e4-8403-8a6b9ab84b3e.png)

If the user select "Don't show again" and click "Close" or if he complete the wizard and click "Finish", the wizard will not show up again. But if the user only close the wizard, it will be show at every logon. The numbers on the left (in circles) will only be there to display the pages of the wizard (current one in gray)

I thought reuse the jQuery ColorBox. Should I ? 
Any suggestions, comments will be very appreciated.

**Comment by ryno83** [comment]
_From @MorrisJobke on May 18, 2015 7:16_

@ryno83 @owncloud/designers Maybe we should include this into the first run wizard? ;)

**Comment by ryno83** [comment]
_From @enoch85 on May 18, 2015 10:32_

@ryno83  Looks very good. Nice improvment. Just one thing, the new password shoud be typed two times, in case if misstakes.

**Comment by ryno83** [comment]
@MorrisJobke @owncloud/designers I think so !

**Comment by ryno83** [comment]
@enoch85 I agree with you !

**Comment by ryno83** [comment]
_From @jancborchardt on May 19, 2015 13:55_

@ryno83 nice work! Just a few things:

* As @MorrisJobke also said, we should combine this with the [first run wizard](https://github.com/owncloud/firstrunwizard). Or rather, build it in there directly (instead of core)
* Basically you can boil it down to one screen which is a combination of the first run wizard and the personal detail fields. Some things can be removed:
  * The first screen is not really of use since it just introduces the concept of a wizard. I’d directly start with the second where you put in your info
  * The Notifications settings are pretty well set by default, so I don’t see a need to show them here.
  * Similarly, the password shouldn’t even be changeable here as it’s not important – you just logged in with it. We only need to ask for things which are _not_ there already. ;)
* Add the profile image adding! That’s very important for sharing.
* Also let people know their remote sharing url (like `username@example.com/owncloud` cc @schiesbn)

**Comment by scolebrook** [comment]
@ryno83 Love the idea and the design. Please make this themeable and remember that everything except language will be unchangeable for directory users. If the user is an ldap user then either those fields should be grayed out or not even visible. Not visible would be much better to avoid the inevitable support tickets to help desks asking "Why can't I change my email address or password?"

And please don't lose the links to download clients. I know they appear in Personal but having them appear at the end of this new first run wizard, considering that's almost always going to be the next step, is a better user experience than requiring users to discover the links themselves.

**Comment by jancborchardt** [comment]
As per my comment, it’s just gonna be one simple modal screen, no extra colors or stuff. Themability will be possible by CSS always.

**Comment by scolebrook** [comment]
@jancborchardt Missed that. Thanks for clarifying.

**Comment by enoch85** [comment]
> The first screen is not really of use since it just > introduces the concept of a wizard. I’d directly start with > the second where you put in your info

Replace the first screen with the one thats present today, and add the info about the wizard.

**Comment by jancborchardt** [comment]
@enoch85 most people will probably miss the info about the second step (let’s stop calling it »wizard« btw ;)
I would say we improve the design of what is shown on first run, and integrate the fields needed into it:
* Email
* Full name
* If we can, the account image

**Comment by enoch85** [comment]
@jancborchardt Ok, that sounds fair.

What about the ability to change password in the ~~wizard.~~?

**Comment by jancborchardt** [comment]
@enoch85 :D 
As said above about the password:
> Similarly, the password shouldn’t even be changeable here as it’s not important – you just logged in with it. We only need to ask for things which are not there already. ;)

For example the language sweitcher is not needed there either as that is automatically fetched from the browser anyway.

**Comment by ryno83** [comment]
A new one ! With only one page. I needed to resize the page and move "apps things" to the left to have enought space to include the profile picture. For LDAP users, I thought to display the current page because they have nothing to change.
![welcome](https://cloud.githubusercontent.com/assets/11739049/7731760/af810bde-fef0-11e4-958c-3397f8a1b421.png)

**Comment by MorrisJobke** [comment]
@ryno83 This looks really really nice :+1:

**Comment by ryno83** [comment]
@jancborchardt, @enoch85 For the password, imo, it would be a nice improvement because in our organisation, we use LDAP and local users. When I create a local user, I use a random generated password. These passwords are hard to remember and people want to change them. With this feature included on the firstrun, they will have the opportunity to change their password at first login.

**Comment by ryno83** [comment]
@jancborchardt About the name, if we don't use "wizard" anymore, should we rename the app ? I thought about "firstrun" or "welcome". Should we rename (I don't know if it's possible) or create a new github repository ?

**Comment by enoch85** [comment]
True. I'm just to distracted to read properly now. :)

**Comment by jancborchardt** [comment]
@ryno83 wow dude! That’s some really great improvement! :) I would only change some minor wording and layout issues – but we can do that in a pull request.

From my point of view this is a great mockup to use as starting point for a pull request to make this real. @ryno83 you wanna do that? You can already open a pull request when it’s still work in progress so that you get early feedback.

You’re also very welcome in our IRC channel #owncloud-design (on freenode)! :)

**Comment by jancborchardt** [comment]
@ryno83 @j-ed @enoch85 is someone of you interested in implementing this? Otherwise I assume it’s not relevant anymore? :)

**Comment by ryno83** [comment]
Hi @jancborchardt ,
I tried to do it but you asked me to separate my changes into differents PR. Thats what i've done with integration of a controller in PR #32. Since that, I've never received any feedback from you guys. If I'm doing things the wrong way, please tell me. I'm here to learn and to help !

**Comment by jancborchardt** [comment]
@ryno83 cool! Very sorry – we must have missed that pull request. You are also welcome in our IRC channel #owncloud-dev to get feedback and help from other devs. :)

**Comment by enoch85** [comment]
@ryno83 What's up with this, still developing?

**Comment by hurradieweltgehtunter** [comment]
Will take care of it in a general rewrite: https://github.com/owncloud/firstrunwizard/issues/147
