### ISSUE TITLE
Remove Links to Calendar and Contacts if these apps are not installed

### ISSUE THREAD

**Issue by aspdye** [owncloud/firstrunwizard#44]
The wizard shows up to links 2o Calendar and Contacts - also, if these apps are not installed :wink:
There are several ways to fix:
- Do not show if Calendar and Contacts (Frontends) are not enabled.
- Link Admin to Appstore where he can install Calendar and Contacts (Frontends) 
- Leave the buttons and link them to the CalDAV and CardDAV Links (because the backends are included in core since 9.0.0) - but i don't know if they work if the frontends are not installed :confused: 

cc @jancborchardt @DeepDiver1975

**Comment by PVince81** [comment]
The backends do work if the frontends are not installed (I used them actively on my server this way).

The dialog should rather point to documentation about the endpoints, not the apps, since this is about syncing not about managing calendars/contacts in the web UI.
