### ISSUE TITLE
First run wizard doesn’t resize with window

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/firstrunwizard#45]
When zooming in/out on the desktop or changing orientation of a tablet/phone, the first run wizard modal does not resize accordingly.

cc @owncloud/javascript maybe should react to onresize action? This is quite important for a nice first run experience. :)

**Comment by hurradieweltgehtunter** [comment]
Will take care of it in a general rewrite: https://github.com/owncloud/firstrunwizard/issues/147
