### ISSUE TITLE
Infinite loading of the first run wizard...

### ISSUE THREAD

**Issue by Lordmau5** [owncloud/firstrunwizard#51]
### Steps to reproduce
1. Fresh instance of Owncloud
2. Login to the first (or any new) user
3. Get an infinite loading screen

### Expected behaviour
**Not** cause an infinite loading screen and show the first run wizard

### Actual behaviour
It loads infinitely and tries to access a bunch of files (visible in the network tab)

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
nginx 1.10.0

**Database:**
MySQL 5.7.11.0

**PHP version:**
7.0.8

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
https://owncloud.org/

**Signing status (ownCloud 9.0 and above):**
If it's in the admin panel, I can't have a look at that.

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocks50vqiei3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.lordmau5.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.lordmau5.com",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope

**Are you using encryption:** yes/no
Cloudflare

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope

### Client configuration
**Browser:**
Chrome + Firefox, both cause the same issue

**Operating system:**
Windows 10

#### Web server error log
---

#### ownCloud log (data/owncloud.log)
{"reqId":"tP+MEGTjNu6EM22jWX6V","remoteAddr":"162.158.89.202","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user$

#### Browser log
_"A picture is worth a thousand words, what about a video? ..."_
https://i.lordmau5.com/1470395302-1827

**Comment by PVince81** [comment]
Weird. How did you install the wizard ? It seems it's not finding the required JS libraries

**Comment by Lordmau5** [comment]
This was caused by an issue on this one https://github.com/owncloud/core/issues/25748

After I managed to fix that with the `fastcgi_params`, this issue vanished as well.

I completely forgot to close it though, haha, my bad :D
