### ISSUE TITLE
First user run, dialog on browser.

### ISSUE THREAD

**Issue by UnMenorqui** [owncloud/firstrunwizard#64]
Hi!

I recently configured owncloud at my work, and i've got like 129 usersnow, and it's gonna get bigger as users join in, and for the first time they log in, it appears de "personal.php" template, which shows information about getting the Android, ios, or windows app. As i work in a university, we can't show this kind of blurb. 

By the way, i just achieved that this page is getting diplayed with the "Can't load content" Waring, but i'd like this 'pop-up' not to show, is there any thing i can do?

Thanks!

**Comment by hurradieweltgehtunter** [comment]
Sorry that you never received an answer.
Will take care of it in a general rewrite: https://github.com/owncloud/firstrunwizard/issues/147
