### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by tomneedham** [owncloud/firstrunwizard#73]
<img width="630" alt="screen shot 2018-02-27 at 19 44 11" src="https://user-images.githubusercontent.com/660805/36750939-ad59c87a-1bf6-11e8-83f6-827778efb3c8.png">
@ core/83bad77b16952fd4c5df2f1ea2bef1a587362f13 

<img width="493" alt="screen shot 2018-02-27 at 19 45 07" src="https://user-images.githubusercontent.com/660805/36750959-bccde16a-1bf6-11e8-96d2-872cc28916b5.png">

cc @felixheidecke @PVince81 

guessed p2 since this gives a bad impression right at the start of using owncloud

**Comment by tomneedham** [comment]
seems core uses .png not .svg

**Comment by felixheidecke** [comment]
Fixed in https://github.com/owncloud/core/pull/30958 and https://github.com/owncloud/firstrunwizard/pull/75
