### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/firstrunwizard#78]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Removed

`.live()`

- [ ] /js/firstrunwizard.js
- [ ] /js/jquery.colorbox.js

## Minor

`.trigger()`

- [ ] /js/jquery.colorbox.js

`.click()`

- [ ] /js/jquery.colorbox.js

`.focus()`

- [ ] /js/jquery.colorbox.js

`.ajax()`

- [ ] /js/firstrunwizard.js

`.data()`

- [ ] /js/jquery.colorbox.js

`.focus()`

- [ ] /js/jquery.colorbox.js

`.attr()`

- [ ] /js/jquery.colorbox.js

`.add()`

- [ ] /js/jquery.colorbox.js

`.replaceWith()`

- [ ] /js/jquery.colorbox.js

`.appendTo()`

- [ ] /js/jquery.colorbox.js

`.insertBefore()`

- [ ] /js/jquery.colorbox.js

**Comment by PVince81** [comment]
hmmm... do we need to upgrade colorbox maybe ?

**Comment by VicDeo** [comment]
@PVince81 well, I can upgrade colorbox, despite the fact it is jQuery 1.9-ready
the current version is the same 1.6.4 but has fixes for two typos in comments :)
