### ISSUE TITLE
[decouple] First run wizard 1.2.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/firstrunwizard#97]
When taking care of a task (and marking as done), please add your name to the task!

### Reason

- Decouple release cycle from code
- new occ command https://github.com/owncloud/firstrunwizard/pull/83

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan"

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number: https://github.com/owncloud/firstrunwizard/pull/103

**Comment by PVince81** [comment]
1.2.0RC1: https://github.com/owncloud/firstrunwizard/releases/tag/v1.2.0RC1

**Comment by PVince81** [comment]
Note: the RC is NOT signed

- [ ] TODO: generate signing key before rebuilding final tarball

**Comment by PVince81** [comment]
stable10 to master diff is close, low risk. locking stable10 now, we'll use master for future

**Comment by PVince81** [comment]
assigned @dpakach for regression testing

**Comment by dpakach** [comment]
Firstrunwizard testplan for 1.2.0RC1 
Issue - https://github.com/owncloud/firstrunwizard/issues/102
PR - https://github.com/owncloud/QA/pull/616

**Comment by PVince81** [comment]
final here: https://github.com/owncloud/firstrunwizard/releases/tag/v1.2.0
